name: mobile_frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
    
  http: ^1.2.2  # Check for the latest version
  english_words: ^4.0.0
  provider: ^6.0.0
  google_maps_flutter: ^2.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.0.18 # or the latest version
  geolocator: ^9.0.0
  geolocator_android: ^4.6.1
  geolocator_apple: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
