name: mobile_frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  http: ^1.2.2  # Check for the latest version
  english_words: ^4.0.0
  provider: ^6.0.0
  google_maps_flutter: ^2.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.0.18 # or the latest version
  geolocator: ^13.0.1
  geolocator_android: ^4.6.1
  geolocator_apple: ^2.3.0
  mime: ^2.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_map_location_marker: any
  flutter_spinkit: ^5.0.0
  cached_network_image: ^3.2.0
  mockito: ^5.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading.png
    - assets/background.png


